#!/usr/bin/env python3
"""Regenerate the private demo-preview gallery from a manifest.

    ops/build-demo-gallery.py [MEDIA_DIR]     default: /tmp/overboard-media

The gallery is a single self-contained index.html: a reverse-chronological
timeline of clips, newest first, each with a title that says what CHANGED
rather than what it is. Served privately over Tailscale; nothing is published.

Why a generator rather than hand-edited HTML: the page is rewritten every time
a clip lands, and hand-editing it during a launch push is exactly how a stale
or broken page ends up in front of someone. Add a row to clips.json, re-run,
done.

The `PLAYABLE SIM` declaration is baked into the template on purpose. Every
clip here is Playable Sim footage, and the five lines must travel with it --
if this HTML is ever persisted for a public purpose (the CEO has flagged that
as a maybe), the declaration is already attached rather than being something
someone has to remember to add. See overboard#163.
"""
import json
import os
import sys

MEDIA = sys.argv[1] if len(sys.argv) > 1 else "/tmp/overboard-media"
MANIFEST = os.path.join(MEDIA, "clips.json")

DECLARATION = [
    "The steering is invented — the simulated wheel is a cylinder and physically cannot carve.",
    "The wheel is widened for playability, a deliberate divergence from the hardware model.",
    "The rider is a rigid ballast, not a person.",
    "Nobody has ridden anything, because no hardware exists.",
    "The board’s ground path is dead-reckoned, not simulated.",
]

HEAD = """<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Overboard — demo timeline</title>
<style>
 :root{{--bg:#0d0d0f;--card:#17171b;--line:#2a2a31;--fg:#ececf1;--dim:#8b8b96;--accent:#4da3ff}}
 *{{box-sizing:border-box}}
 body{{font:16px/1.5 -apple-system,BlinkMacSystemFont,system-ui,sans-serif;background:var(--bg);color:var(--fg);margin:0;padding:20px 16px 60px}}
 header{{max-width:820px;margin:0 auto 22px}}
 h1{{font-size:22px;margin:0 0 4px;letter-spacing:-.02em}}
 .sub{{color:var(--dim);font-size:13px}}
 .decl{{max-width:820px;margin:0 auto 26px;background:#241c00;border:1px solid #5a4700;border-radius:10px;padding:12px 14px;font-size:12.5px;line-height:1.55}}
 .decl b{{color:#ffd479;letter-spacing:.04em}}
 .decl ul{{margin:8px 0 0;padding-left:18px}} .decl li{{margin:2px 0;color:#d9cfae}}
 main{{max-width:820px;margin:0 auto;position:relative}}
 .item{{position:relative;padding-left:26px;margin-bottom:26px}}
 .item::before{{content:"";position:absolute;left:5px;top:9px;width:9px;height:9px;border-radius:50%;background:var(--accent)}}
 .item::after{{content:"";position:absolute;left:9px;top:22px;bottom:-26px;width:1px;background:var(--line)}}
 .item:last-child::after{{display:none}}
 .when{{color:var(--dim);font-size:12px;letter-spacing:.03em;text-transform:uppercase}}
 .title{{font-size:17px;font-weight:640;margin:1px 0 5px;letter-spacing:-.01em}}
 .note{{color:var(--dim);font-size:13.5px;margin-bottom:10px}}
 .card{{background:var(--card);border:1px solid var(--line);border-radius:12px;overflow:hidden}}
 video{{width:100%;display:block;background:#000}}
 .missing{{padding:26px 14px;color:var(--dim);font-size:13px;text-align:center}}
 footer{{max-width:820px;margin:34px auto 0;color:var(--dim);font-size:12px;border-top:1px solid var(--line);padding-top:14px}}
</style></head><body>
<header>
 <h1>Overboard — demo timeline</h1>
 <div class="sub">Newest first. Private to the tailnet — nothing here is published.</div>
</header>
<div class="decl"><b>PLAYABLE SIM</b> — computer graphics driven by a simulator running live, responding to input. Not reproducible, and not a controls result.
 <ul>{decl}</ul>
</div>
<main>
"""

FOOT = """</main>
<footer>Regenerated by <code>ops/build-demo-gallery.py</code>. Add a clip to <code>clips.json</code> and re-run.</footer>
</body></html>
"""


def main():
    if not os.path.exists(MANIFEST):
        print(f"no manifest at {MANIFEST}")
        return 1
    clips = json.load(open(MANIFEST))
    # Newest first. Explicit `order` wins over date so same-day clips stay sequenced.
    clips.sort(key=lambda c: (c.get("date", ""), c.get("order", 0)), reverse=True)

    out = [HEAD.format(decl="".join(f"<li>{d}</li>" for d in DECLARATION))]
    for c in clips:
        f = c.get("file", "")
        present = f and os.path.exists(os.path.join(MEDIA, f))
        poster = c.get("poster", "")
        pa = f' poster="{poster}"' if poster and os.path.exists(os.path.join(MEDIA, poster)) else ""
        body = (
            f'<video controls preload="metadata"{pa} src="{f}"></video>'
            if present
            else '<div class="missing">clip not captured yet</div>'
        )
        out.append(
            f'<div class="item"><div class="when">{c.get("date","")}</div>'
            f'<div class="title">{c.get("title","(untitled)")}</div>'
            f'<div class="note">{c.get("note","")}</div>'
            f'<div class="card">{body}</div></div>\n'
        )
    out.append(FOOT)
    open(os.path.join(MEDIA, "index.html"), "w").write("".join(out))
    print(f"wrote {MEDIA}/index.html  ({len(clips)} clips)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
