"""Bring the X7 build's look into the MuJoCo model.

Copies the hardware track's per-material meshes and look.json (one board look
for MuJoCo, the Unreal renders and the game; matched to the blog) into
sim/models/meshes/openwheel/x7/, and writes x7_visual.xml there: a fragment
with three parts that sim-host `--plant x7` splices into the model:

    <!-- X7 ASSETS -->  materials and meshes
    <!-- X7 FRAME -->   visual geoms on the frame body
    <!-- X7 WHEEL -->   visual geoms on the (rotating) wheel body

look.json gives sRGB base colours, metallic, roughness, clearcoat and an
emission colour and strength. MuJoCo has no PBR, so: rgba = base colour (the
emission colour for LEDs), specular and shininess from metallic and
roughness, emission = strength / 3.5 (the brightest LED is 1.0). Meshes are
metres, Z up, +X nose, origin = ground under the axle; the geoms sit at
(0, 0, -0.146) and turn 180 deg about Z, because the model's forward is -X.

    $PY sim/carve/x7_look.py [SRC_DIR]
Default SRC_DIR: overboard-viz-kit/out/kit-guide/models/by_material.
"""
import json
import shutil
import sys
from pathlib import Path

SRC = Path(sys.argv[1] if len(sys.argv) > 1 else
           '/Users/mike/projects/overboard-viz-kit/out/kit-guide/models/by_material')
DST = Path(__file__).resolve().parents[1] / 'models' / 'meshes' / 'openwheel' / 'x7'


def rgb(h):
    h = h.lstrip('#')
    return tuple(int(h[i:i + 2], 16) / 255.0 for i in (0, 2, 4))


def main():
    look = json.load(open(SRC / 'look.json'))
    DST.mkdir(parents=True, exist_ok=True)
    for old in DST.glob('*.stl'):
        old.unlink()
    shutil.copy(SRC / 'look.json', DST / 'look.json')
    mats = look['materials']
    brightest = max(m['emission_strength'] for m in mats.values()) or 1.0
    assets, geoms = [], {'frame': [], 'wheel': []}
    for name, m in mats.items():
        led = m['emission_strength'] > 0
        c = rgb(m['emission_color'] if led and m['emission_color'] else m['base_color'])
        spec = min(1.0, 0.15 + 0.6 * m['metallic'] * (1 - m['roughness']) + 0.3 * m['clearcoat'])
        shine = max(0.05, 1.0 - m['roughness'])
        emis = m['emission_strength'] / brightest if led else 0.0
        assets.append(f'<material name="x7_{name}" rgba="{c[0]:.3f} {c[1]:.3f} {c[2]:.3f} 1" '
                      f'specular="{spec:.2f}" shininess="{shine:.2f}" emission="{emis:.2f}"/>')
    for f in look['files']:
        shutil.copy(SRC / f['file'], DST / f['file'])
        mesh = Path(f['file']).stem
        assets.append(f'<mesh name="x7_{mesh}" file="x7/{f["file"]}"/>')
        geoms[f['body']].append(
            f'<geom name="x7_{mesh}" class="visual" type="mesh" mesh="x7_{mesh}" '
            f'material="x7_{f["material"]}" pos="0 0 -0.146" euler="0 0 180"/>')
    out = ['<!-- Generated by sim/carve/x7_look.py from the hardware track\'s look.json. -->',
           '<!-- X7 ASSETS -->', *assets, '<!-- X7 FRAME -->', *geoms['frame'],
           '<!-- X7 WHEEL -->', *geoms['wheel']]
    (DST / 'x7_visual.xml').write_text('\n'.join(out) + '\n')
    print(f"{len(look['files'])} meshes, {len(mats)} materials -> {DST}")


if __name__ == '__main__':
    main()
