[package]
name = "board-app-driverless"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "board-app-driverless"
path = "src/main.rs"

[[bin]]
name = "impulse-response-rust"
path = "src/bin/impulse-response-rust.rs"

[dependencies]
board-types = { workspace = true }
hal = { workspace = true }
hal-actuate = { workspace = true }
control-core = { workspace = true }
safety = { workspace = true }
sim-backend = { workspace = true }
